name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd Example
          xcodebuild  -project PermissionDirectorExample.xcodeproj -scheme PermissionDirectorExample  -derivedDataPath build -configuration -arch arm64 Debug clean build CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED="NO" CODE_SIGN_IDENTITY="" CODE_SIGN_ENTITLEMENTS=""
